### ISSUE TITLE
Enemy AI prototype

### ISSUE THREAD

**Issue by oscarnt4** [analopesmartinez/ALGame#3]

**Comment by b1ngggg** [comment]
**·**Created a capsule as the player and moved the main camera to be the child of the player. 
**·**Created a cube as the enemy NPC temporarily. 
**·**Created three C# scripts inside the enemy AI folder, MouseLook1 for the camera, RigidbodyMove for the player movement temporarily for testing, and NPCcontrol for the enemy NPC AI. 
**·**The speed of player movement, sensitivity of the mouseXY, enemy freeze time, enemy normal speed, and enemy chase speed can be modified inside the scripts which include comments. 
**·**Included animation control for future development
**·**The scene has been saved as "Bing" in the Assets folder
